version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    container_name: pokemon-backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pokemon_db
    depends_on:
      - mongo
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: pokemon-frontend
    ports:
      - "3000:3000"

    depends_on:
      - backend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  mongo_data:
