version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: pokemon-backend
    ports:
      - "5001:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/pokemon_db
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    working_dir: /app
    command: npm start

  frontend:
    build: ./frontend
    container_name: pokemon-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./frontend:/node_modules:/app/node_modules
    working_dir: /app
    command: npm start

volumes:
  mongo_data:
